SET SESSION storage_engine = "InnoDB";
SET SESSION time_zone = "+7:00";
ALTER DATABASE CHARACTER SET "utf8";

DROP TABLE IF EXISTS user;
CREATE TABLE user (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS player;
CREATE TABLE player (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    mac VARCHAR(20) NOT NULL UNIQUE,
    ip VARCHAR(30) NOT NULL,
    owner VARCHAR(100) DEFAULT NULL
);

DROP TABLE IF EXISTS playlist;
CREATE TABLE playlist (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    playlist_name VARCHAR(100) NOT NULL ,
    player_id VARCHAR(4) NOT NULL
);


DROP TABLE IF EXISTS file;
CREATE TABLE file (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL ,
    player_ip VARCHAR(20) NOT NULL,
    playlist VARCHAR(20) NOT NULL,
    duration VARCHAR(20) DEFAULT NULL
);